# raa_class_mapping.py
# Mapping of RAÄ archaeological site classes from Swedish to English
# Covers ~200 classes based on RAÄ official terminology

RAA_CLASS_MAPPING = {
    "Avrättningsplats": "Execution site",
    "Ballastplats": "Ballast site",
    "Begravningsplats": "Cemetery",
    "Begravningsplats enstaka": "Single burial site",
    "Bengömma": "Bone cache",
    "Bergshistorisk lämning övrig": "Other mining-related site",
    "Bildristning": "Petroglyph / rock carving",
    "Björngrav": "Bear grave",
    "Blästbrukslämning": "Bloomery remains",
    "Blästplats": "Bloomery site",
    "Boplats": "Settlement site",
    "Boplatsgrop": "Settlement pit",
    "Boplatslämning övrig": "Other settlement remains",
    "Boplatsområde": "Settlement area",
    "Boplatsvall": "Settlement rampart",
    "Borg": "Hillfort / castle",
    "Bro": "Bridge",
    "Brott/täkt": "Quarry",
    "Brunn/kallkälla": "Well / freshwater spring",
    "Brytningsyta": "Extraction surface",
    "Bytomt/gårdstomt": "Village or farmstead plot",
    "Båtlänning": "Boat landing site",
    "Dammvall": "Dam embankment",
    "Depåfynd": "Deposit find",
    "Dike/ränna": "Ditch / trench",
    "Drag": "Dragway / haul path",
    "Fartygs-/båtlämning": "Shipwreck / boat remains",
    "Fiskeläge": "Fishing settlement",
    "Flatmarksgrav": "Flat-ground grave",
    "Flintgruva": "Flint mine",
    "Flottningsanläggning": "Log driving installation",
    "Fornborg": "Ancient fort",
    "Fornlämningsliknande bildning": "Formation resembling ancient monument",
    "Fornlämningsliknande lämning": "Remains resembling ancient monument",
    "Fossil åker": "Ancient field",
    "Fyndplats": "Find spot",
    "Fyndsamling": "Artifact collection",
    "Fyr": "Lighthouse / beacon",
    "Fångstanläggning övrig": "Other trapping structure",
    "Fångstgrop": "Pitfall trap",
    "Fångstgropssystem": "Pitfall trap system",
    "Fångstgård": "Hunting enclosure",
    "Fäbod": "Mountain pasture settlement",
    "Färdväg": "Historic road",
    "Färdvägssystem": "Historic road system",
    "Fästning/skans": "Fortification / redoubt",
    "Förtöjningsanordning": "Mooring device",
    "Förvaringsanläggning": "Storage facility",
    "Gistgård": "Fish-drying rack",
    "Gjuteri": "Foundry",
    "Glasindustri": "Glass industry site",
    "Gravfält": "Grave field / burial ground",
    "Gravhägnad": "Grave enclosure",
    "Gravklot": "Grave sphere",
    "Grav markerad av sten/block": "Stone-marked grave",
    "Grav- och boplatsområde": "Burial and settlement area",
    "Grav - uppgift om typ saknas": "Grave (unspecified type)",
    "Gravvård": "Gravestone / grave marker",
    "Grav övrig": "Other grave type",
    "Gruvhål": "Mine shaft",
    "Gruvområde": "Mining area",
    "Gränsbestämt område": "Boundary-defined area",
    "Gränsmärke": "Boundary marker",
    "Hammare/smedja": "Hammer forge / smithy",
    "Hammarområde": "Hammer forge area",
    "Hamnanläggning": "Harbor installation",
    "Hamnområde": "Harbor area",
    "Hornsamling": "Horn collection",
    "Husgrund, förhistorisk/medeltida": "House foundation, prehistoric/medieval",
    "Husgrund, historisk tid": "House foundation, historical period",
    "Hyttlämning": "Smelting hut remains",
    "Hytt- och hammarområde": "Smelting hut and forge area",
    "Hyttområde": "Smelting hut area",
    "Hägnad": "Enclosure",
    "Hägnadssystem": "Enclosure system",
    "Hällmålning": "Rock painting",
    "Hällristning": "Rock carving / petroglyph",
    "Härd": "Hearth / fire pit",
    "Hög": "Burial mound",
    "Industri övrig": "Other industrial remains",
    "Järnåldersdös": "Iron Age dolmen",
    "Kalkugn": "Lime kiln",
    "Kanal": "Canal",
    "Kanalmärke": "Canal marker",
    "Kemisk industri": "Chemical industry site",
    "Kloster": "Monastery",
    "Kokgrop": "Cooking pit",
    "Kolningsanläggning": "Charcoal production site",
    "Kompassros/väderstreckspil": "Compass rose / directional marker",
    "Kraftindustri": "Power industry",
    "Kvarn": "Mill",
    "Kyrka/kapell": "Church / chapel",
    "Kyrkstad": "Church village",
    "Kåta": "Lapp hut / kåta",
    "Källa med tradition": "Sacred spring / traditional well",
    "Labyrint": "Stone labyrinth",
    "Livsmedelsindustri": "Food industry",
    "Luftfarkost": "Aircraft remains",
    "Lägenhetsbebyggelse": "Apartment settlement remains",
    "Metallindustri/järnbruk": "Metal industry / ironworks",
    "Militär anläggning övrig": "Other military installation",
    "Militär mötesplats": "Military assembly site",
    "Minnesmärke": "Memorial monument",
    "Naturföremål/-bildning med bruk, tradition eller namn": "Natural feature with historical or cultural significance",
    "Offerkast": "Offering cairn",
    "Offerplats": "Sacrificial site",
    "Område med fartygslämningar": "Shipwreck area",
    "Område med flottningsanläggningar": "Log driving installation area",
    "Område med fossil åkermark": "Fossil field area",
    "Område med militära anläggningar": "Military installations area",
    "Område med skogsbrukslämningar": "Forestry remains area",
    "Pappersindustri": "Paper industry",
    "Park-/trädgårdsanläggning": "Park / garden",
    "Plats med tradition": "Site with tradition",
    "Rengärda": "Reindeer corral",
    "Renvall": "Reindeer grazing area",
    "Ristning, medeltid/historisk tid": "Historic carving",
    "Runristning": "Rune carving / runestone",
    "Röjningsröse": "Clearing cairn",
    "Röse": "Cairn",
    "Rösning": "Stone clearance",
    "Samlingsplats": "Assembly site",
    "Sjömärke": "Sea mark / navigation marker",
    "Skåre/jaktvärn": "Hunting blind / look-out",
    "Skärvstenshög": "Fire-cracked stone mound",
    "Slagfält": "Battlefield",
    "Slott/herresäte": "Castle / manor house",
    "Smideslämning": "Blacksmithing remains",
    "Smidesområde": "Blacksmithing area",
    "Småindustriområde": "Small industry area",
    "Spärranordning": "Barrier installation",
    "Stadsbefästning": "City fortifications",
    "Stadslager": "Urban cultural layer",
    "Stadsvall/stadsmur": "City rampart / wall",
    "Stalotomt": "Sami settlement",
    "Stenindustri": "Stone industry",
    "Stenkammargrav": "Stone chamber grave",
    "Stenkistgrav": "Stone cist grave",
    "Stenkrets/stenrad": "Stone circle / stone row",
    "Stenring": "Stone ring",
    "Stenröjd yta": "Stone-cleared surface",
    "Stensättning": "Stone setting",
    "Stenugn": "Stone oven",
    "Stridsvärn": "Defensive trench / earthwork",
    "Tegelindustri": "Brickworks",
    "Terrassering": "Terracing",
    "Textilindustri": "Textile industry",
    "Tomtning": "Hut foundation",
    "Träindustri": "Timber industry",
    "Uppfordringsanläggning": "Hoisting facility",
    "Vad": "Wading place / ford",
    "Vallanläggning": "Rampart installation",
    "Varv/slip": "Shipyard / slipway",
    "Viste": "Sami settlement site",
    "Vårdkase": "Signal beacon",
    "Vägmärke": "Road marker",
    "Övrigt": "Other"
}
